### ISSUE TITLE
abort should not call remaining remove hooks.

### ISSUE THREAD

**Issue by trusktr** [josh/selector-observer#15]
When we intend to stop observing, I don't think we intend to call remove hooks, because in this case it doesn't necessarily mean that the elements were removed, just that we want to stop observing.

As another example, `MutationObserver` doesn't trigger changes when disconnected.

**Comment by josh** [comment]
I could see either way, but this was intentional in the original implementation of `abort()`. I mostly use it in tests as a way to teardown the result. So it's not something I can easily change without considering it a backwards incompatible change.
