### ISSUE TITLE
Callbacks not called in IE11

### ISSUE THREAD

**Issue by dhilgarth** [josh/selector-observer#16]
I am currently investigating an issue where my callbacks are not called in IE11.

I think this happens because in IE11, `Element.matches` doesn't exist, so [this branch](https://github.com/josh/selector-observer/blob/master/lib/changes.js#L64) is being executed.  
The issue here is that the node that has been added to the DOM is passed as the parameter to `SelectorSet.queryAll`. The implementation of `SelectorSet.queryAll` uses this node - called `context` there - as the instance on which it calls [`ParentNode.querySelectorAll`](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/querySelectorAll).  
However, `ParentNode.querySelectorAll` only returns the matching **descendants** of the node it was executed on and not the node itself, leading to an empty result.  

Because `SelectorSet.matches` already has a detection for the proprietary names of older browser for `Element.matches` fixing this issue should be as simple as removing that feature detection in `changes.js` so that `SelectorSet.matches` is used unconditionally.

**Comment by dhilgarth** [comment]
It's actually enough to have a polyfill for `Element.matches`. But I think that's not the point. This is a bug and needs fixing.

**Comment by josh** [comment]
I've personally stopped testing on IE11, but if you have a patch that isn't too invasive, I'd be happy to accept it.

**Comment by dhilgarth** [comment]
#17 is my proposal to fix this.

**Comment by josh** [comment]
https://github.com/josh/selector-observer/pull/17
