### ISSUE TITLE
Add a note about disconnect to the docs

### ISSUE THREAD

**Issue by dy** [josh/selector-observer#22]
Now there's no info about disabling created observer.
There's `disconnect` method, but that doesn't seem to clean up selectors.

**Comment by josh** [comment]
The `disconnect` method primarily exists to support the internal tests here. Which is why it hasn't been documented. It's probably fine to use if you want, I'm not planning to change the behavior, but it's not an encouraged API. Thanks!

**Comment by dy** [comment]
Are there any plans on providing a way to disable the observer?

**Comment by josh** [comment]
You can call `abort()` on the object returned from `observe()`
