### ISSUE TITLE
Doesn't trigger all matched nodes by changing attributes

### ISSUE THREAD

**Issue by dy** [josh/selector-observer#25]
```js
import { observe } from "selector-observer";

document.body.innerHTML = "<x><x></x></x>";

observe("x.y", {
  add(el) {
    console.log("x", el);
  }
});

observe("x.y x", {
  add(el) {
    console.log("y", el);
  }
});

requestAnimationFrame(() => document.querySelector("x").classList.add("y"))
```
[Sandbox](https://codesandbox.io/s/wizardly-field-d9dyb?fontsize=14&hidenavigation=1&theme=dark).

The second rule is never triggered here, although it matches.

That happens because this check https://github.com/josh/selector-observer/blob/master/lib/changes.js#L107 matches selector set against changed attrib target, but instead it should revalidate all rules within the `document` to see if any new elements match rules.

**Comment by dy** [comment]
Offtopic: this looks interesting https://github.com/naugtur/insertionQuery

**Comment by tryhardest** [comment]
worth mentioning yes

**Comment by josh** [comment]
Thanks for the report, but yes, this has kinda been a known limitation for a long time. I just haven't documented properly. While some descendant may appear to work in certain cases, I consider them undefined behavior. Only what CSS defines a ["simple selectors"](https://www.w3.org/TR/2018/REC-selectors-3-20181106/#simple-selectors) are supported.
