### ISSUE TITLE
Typing of `observe()` isn't valid

### ISSUE THREAD

**Issue by fregante** [josh/selector-observer#29]
I'd expect to be able to run:

```ts
observe<HTMLImageElement>('img', {
	add(image) {
		console.log(img.src)
	}
});
```

But I get 

```ts
source/features/linkify-user-edit-history-popup.tsx:8:88 - error TS2345: Argument of type '{ add(element: HTMLImageElement): void; }' is not assignable to parameter of type '{ constructor: new () => HTMLImageElement; } & Options<HTMLImageElement>'.
  Type '{ add(element: HTMLImageElement): void; }' is not assignable to type '{ constructor: new () => HTMLImageElement; }'.
    Types of property 'constructor' are incompatible.
      Type 'Function' is not assignable to type 'new () => HTMLImageElement'.
        Type 'Function' provides no match for the signature 'new (): HTMLImageElement'.

  8  observe<HTMLImageElement>('img', {
                                                                                           ~
  9  	add(element) {
    ~~~~~~~~~~~~~~~~
```

Live demo: [`69c0c71` (#3412)](https://github.com/sindresorhus/refined-github/pull/3412/commits/69c0c71d394c66992844d579949ddf0f5fe8acb7)

Probably caused by this _required_ constructor type: https://github.com/josh/selector-observer/blob/b811bb5d13cba9940026430f92a6760d5f9e365c/lib/index.d.ts#L7-L12

**Comment by josh** [comment]
Try this instead:

```ts
observe('img', {
  constructor: HTMLImageElement,       
  add(image) {
    console.log(img.src)
  }
});
```

TypeScript annotations aren't available at runtime, so if you require an specific `HTMLElement` subclass, you can pass it along as a `constructor` filter so other non-images are filtered out.

**Comment by fregante** [comment]
Thank you!

**Comment by fregante** [comment]
> TypeScript annotations aren't available at runtime

However TS annotations are more flexible, for example this isn't currently possible:

```ts
observe('input, button', {
  constructor: HTMLInputElement | HTMLButtonElement,       
  add(image) {
    console.log(img.src)
  }
});
```

**Comment by josh** [comment]
You can always do the type check yourself inside the hook callback.

```typescript
observe('input, button', {
  add(el) {
   if (!(el instanceof HTMLInputElement || el instanceof HTMLButtonElement)) return
   // el is refined as HTMLInputElement | HTMLButtonElement
    console.log(el)
  }
});
```

This was originally how *we* used `observe`, but added the constructor argument as a connivence for simple cases.

**Comment by fregante** [comment]
Right, but runtime checks are lengthy and unnecessary if the selector ends with a tag.
`document.querySelector<HTMLInputElement  | HTMLButtonElement>('input, button')` already does exactly what it needs to do without any further code.

Would you consider making the `constructor` optional in the types?
