### ISSUE TITLE
Why doesn’t `disconnect` call `abort`?

### ISSUE THREAD

**Issue by fregante** [josh/selector-observer#32]
The documentation is scarce around these 2 methods so I assumed they were the same, but in the code it seems that `disconnect()` just disconnects the MutationObserver while `abort()` completely removes the selector from the internal maps. 

Shouldn’t disconnect also do the same since there’s no way to “reconnect” it? Currently it seems that it will just leak. 

This is causing a bug, as described in this comment: https://github.com/sindresorhus/refined-github/issues/4067#issuecomment-792273884

**Comment by kidonng** [comment]
I think there is two cases:


Case 1: you don't need a different rootNode, so you just `import {observe} from 'selector-observer'`. You don't need disconnect() because it will stop everything and the built-in “root observer” is dead for real since you don't have direct access to it.

Case 2: you need a different rootNode, so you create a new "root observer". In this case that rootNode probably will change, so you have access to disconnect(). It's safe to use since you can access the "root observer"  (i.e. observe new rootNode), 

Just my quick thoughts.

**Comment by fregante** [comment]
Case 1 is irrelevant in this case since it doesn’t have a disconnect method. 

For case 2, if you’re offering a constructor that matches MutationObserver’s API, one would expect `disconnect` to kill the entire SelectorObserver, just like MutationObserver.

Instead the current situation requires me to keep track of every `observe' and manually calling abort on them. That doesn’t match MutationObserver observer anymore.

**Comment by fregante** [comment]
I think the bug that linked here was because:

1. SelectorObserver#disconnect called MutationObserver#disconnect, making it look like it worked
2. A successive SelectorObserver#observer added the same observer again and reactivated the MutationObserver, but SelectorSet still had both listeners, so both were called.

**Comment by kidonng** [comment]
The bug linked is just about wrong usage, IMO.

- If you want to specify a rootNode, use new SelectorObserver and use disconnect() to stop watching the rootNode.
- If you want to specify a selector, use observer = SelectorObserver.prototype.observe(), and use observer.abort() to stop watching the selector. 

> A successive SelectorObserver#observer added the same observer again and reactivated the MutationObserver, but SelectorSet still had the previous listener, so both were called — that is, the same selector/callback was called twice

This is a valid cause, but still, it's just not how the library should be used (again, IMO).

**Comment by fregante** [comment]
> The bug linked is just about wrong usage, IMO.

No it's not. Nothing says that one can't use `document` as the rootNode nor it says that there can't be 2 SelectorObserver with the same rootNode. Please stop referring to that issue as it's irrelevant if not for the fact that it's caused by the bug you yourself described:

- `disconnect` does not clean up SelectorSet like one would expect

That's all this issue is about.

**Comment by kidonng** [comment]
Sorry about that. Still, I think this is not a issue of the library itself, it's just not clear in the docs that disconnect() only concerns about rootNode, not the selectors being watched. And the abort() method should definitely be in the docs too.
