### ISSUE TITLE
`handlers.constructor` conflicts with `Object.prototype.constructor`

### ISSUE THREAD

**Issue by razh** [josh/selector-observer#6]
For this line:

https://github.com/josh/selector-observer/blob/1a99318c76267cfb650f6916bc2f3c103e7f085f/lib/selector-observer.js#L68

`klass` will never default to `Element` because all objects have a `constructor` property:

```js
({}).constructor === Object.prototype.constructor
// true
```

**Comment by josh** [comment]
Wow, good catch!

**Comment by razh** [comment]
Thank you @josh! ❤️
